## Numpy

Fixed type and if we make another type to change the whole array will be converted

Effocient

less flexible as compareed to list

In [5]:
L = [1, 2, 3]
print(L)
print(type(L)) # checking the type of list
L2 =[]
for i in L:
    L2.append(str(i)) # converting a list to string
L2

print(L2)
print(type(L2)) # checking the type of list after conversion

[1, 2, 3]
<class 'list'>
['1', '2', '3']
<class 'list'>


In [1]:
import numpy as np
np.__version__

'2.0.2'

In [27]:
np.array([1, 2, 3])

np.array([5, 6, 8], dtype='float32') # specifying the data type while creating an array by assigning dtype we can also convert the data type of the array

# 2D array
np.array([[1, 2, 3], [4, 5, 6]] , dtype='int32')


# Ways to initialize the array
np.zeros((3,4)) # creating an array of zeros with 3 rows and 4 columns
np.ones((3,4)) # creating an array of ones with 3 rows and 4 columns
np.empty((3,4)) # creating an empty array with 3 rows and 4 columns
np.arange(10, 20, 2) # creating an array with a range of values from 10 to 20 with a step of 2
np.linspace(0, 1, 5) # creating an array with 5 values
# equally spaced between 0 and 1
np.eye(3) # creating an identity matrix of size 3x3

# Array attributes
a = np.array([[1, 2, 3], [4, 5, 6]])
a.ndim # number of dimensions
a.shape # shape of the array
a.dtype # data type of the array
a.size # number of elements in the array
a.itemsize # size of each element in bytes
a.nbytes # total size of the array in bytes
a.reshape(3, 2) # reshaping the array to 3 rows and 2 columns
a.flatten() # flattening the array to 1D
a.T # transpose of the array
a.astype('float32') # converting the data type of the array to float32
a.tolist() # converting the array to a list
a.copy() # creating a copy of the array
a.view() # creating a view of the array
a.sum() # sum of all elements in the array
a.min() # minimum value in the array
a.max() # maximum value in the array
a.mean() # mean of all elements in the array
a.std() # standard deviation of all elements in the array
a.var() # variance of all elements in the array
np.unique(a) # unique elements in the array
np.sort(a) # sorting the array
np.concatenate((a, a), axis=0) # concatenating two arrays along rows
np.concatenate((a, a), axis=1) # concatenating two arrays along columns
np.vstack((a, a)) # stacking two arrays vertically
np.hstack((a, a)) # stacking two arrays horizontally
np.split(a, 2) # splitting the array into two equal parts
np.where(a > 3) # indices of elements greater than 3
np.extract(a > 3, a) # extracting elements greater than 3
np.nonzero(a) # indices of non-zero elements
np.save('array.npy', a) # saving the array to a file
np.load('array.npy') # loading the array from a file
# np.savez('array.npz', a=a, b=b) # saving multiple arrays to a file
# np.load('array.npz') # loading multiple arrays from a file
# np.savetxt('array.txt', a) # saving the array to a text file
# np.loadtxt('array.txt') # loading the array from a text file
# np.genfromtxt('array.txt') # loading the array from a text file with missing values
# np.savetxt('array.csv', a, delimiter=',') # saving the array to a CSV file
# np.genfromtxt('array.csv', delimiter=',') # loading the array from a CSV file
np.random.rand(3, 4) # creating an array with random values between 0 and 1
np.random.randint(0, 10, (3, 4)) # creating an array with random integers between 0 and 10
np.random.normal(0, 1, (3, 4)) # creating an array with random values from a normal distribution with mean 0 and standard deviation 1
np.random.uniform(0, 1, (3, 4)) # creating an array with random values between 0 and 1
np.random.seed(42) # setting the seed for random number generation
np.random.rand(3, 4) # creating an array with random values between 0 and 1



array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
       [0.15601864, 0.15599452, 0.05808361, 0.86617615],
       [0.60111501, 0.70807258, 0.02058449, 0.96990985]])

3d arrays

In [2]:
import numpy as np

x3 = np.random.randint(10, size=(3, 4))
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  2
x3 shape:  (3, 4)
x3 size:  12


Array Indexing

In [4]:
x1 = np.array([1, 2, 3, 4, 5, 7, 8, 9, 10, 11])

x1[-1]  # accessing the last element of the array
print(x1[-1])

11


In [ ]:
x2 = np.array([[1, 2, 3, 4, 5],
               [6, 7, 8, 9, 10],
               [11, 12, 13, 14, 15]])

print(x2[1, -2]) # accessing the second last element of the second row of the array

9


Array Slicing

1D Slicing

In [ ]:
# x[start:stop:step]

arr = np.arange(0, 10)
print(arr)
print(arr[:5]) # first five elements
print(arr[5:]) # last five elements
print(arr[1:4]) # middle elements from index 1 to index 3
print(arr[1:4:2]) # accessing elements from index 1 to index 3 with a step of 2
print(arr[::2]) # accessing all elements with a step of 2
print(arr[::-1]) # accessing all elements in reverse order
print(arr[1::3]) # accessing elements from index 1 to the end with a step of 3

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[5 6 7 8 9]
[1 2 3]
[1 3]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]
[1 5 9]


2D Slicing

In [ ]:
arrayko = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arrayko[:2 , :3]) # 2 rows and 3 columns

print(arrayko[:3 , 1::2]) # 3 rows and every other column starting from the second column between index 1 and index 2

print(arrayko[:3 , ::2]) # 3 rows and every other column starting from index 0

[[1 2 3]
 [4 5 6]]
[[2]
 [5]
 [8]]
[[1 3]
 [4 6]
 [7 9]]
